---
- hosts: all
  become: true

  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - ufw
        state: latest
        update_cache: true

    - name: "UFW - Allow ports"
      community.general.ufw:
        rule: allow
        port: '{{ item }}'
        proto: tcp
      loop:
        - "443"
        - "80"
        - "22"

    - name: UFW - Set logging
      community.general.ufw:
        logging: 'on'

    - name: UFW - Rejection handling
      community.general.ufw:
        rule: reject
        port: auth
        log: yes

    - name: UFW - Enable
      community.general.ufw:
        state: enabled